import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: process.env.NODE_ENV === 'development' 
    ? '🔧 PZE (DEV)' 
    : 'Projektzeiterfassung',
}

//export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//x};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
// Auto-Deploy Test Mo.  8 Dez. 2025 09:04:36 CET
// Auto-Deploy Test 3 Mo.  8 Dez. 2025 09:46:18 CET
